import Head from 'next/head'
import { Inter } from '@next/font/google'
import axios from 'axios'
import Home from '@/components/home/Home'

const inter = Inter({ subsets: ['latin'] })

export default function Index({categoryList, productList}) {
  return (
    <>
      <Head>
        <title>Demo Matbaa Sitesi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home productList={productList} categoryList={categoryList}/>
      
    </>
  )
}

export const getServerSideProps = async () => {
  
  const category = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
  const product = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`)

  return {
    props: {
      categoryList: category.data ? category.data : [],
      productList: product.data ? product.data : []
    }
  }
} 
